# Generated by Django 4.0.4 on 2022-05-20 18:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_user_is_artist_user_is_reviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('song_title', models.CharField(max_length=50)),
                ('video_id', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('favorite_verse', models.CharField(max_length=100)),
                ('favorite_instrument', models.CharField(max_length=50)),
                ('rating', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('overview', models.CharField(max_length=500)),
                ('song', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='mulo.song')),
            ],
        ),
    ]
