# Generated by Django 4.0.4 on 2022-05-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mulo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='stage_name',
            field=models.CharField(default='Artist Name', max_length=100),
        ),
    ]
