# Generated by Django 4.0.4 on 2022-05-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mulo', '0002_song_stage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewer',
            old_name='favorite_verse',
            new_name='favorite_lyric',
        ),
    ]
